JS-32-add SortDropdown
ss21-js/ss21-js-frontend pull request #15
Opened 2021-04-26 15:41 UTC by Veronika-Starkulla

SortDropdown erstellt

2021-04-26 16:34 UTC, DevNico requested changes

2021-04-26 16:34 UTC, DevNico commented on src/components/app/SortAttributes.tsx
> +		<Select open={open} onClose={handleClose} onOpen={handleOpen} defaultValue={1}>
Für deutlich bessere performance auf mobilen Geräten sollte man entweder ein `NativeSelect` oder das normale `Select` mit dem `native` prop verwenden.

2021-04-26 16:34 UTC, DevNico commented on src/model/attribute.ts
> +}
Der Name `Attribute` ist im globalen models Ordner nicht sonderlich deskriptiv. Ich denke das wir das auch nicht außerhalb vom `SortDropdown` brauchen werden, daher würde ich es auch direkt beim `SortDropdown` lassen. Trotzdem wäre ein Name wie `SortOption` besser.

Außerdem würde ich statt einem numerischen index hier eher einen string key bevorzugen.

2021-04-26 16:34 UTC, DevNico commented on src/components/app/SortAttributes.tsx
> +const SortAttributes: React.FC<SortAttributesProps> = ({ attributes, onClick }) => {
Ich finde den Namen `SortAttributes` unpassend `SortOptions` entspricht eher dem Nutzen der Komponente.

2021-04-26 16:34 UTC, DevNico commented on src/components/app/SortAttributes.tsx
> +	onClick?: () => void;
Die `Select` Komponente hat einen `onChange` callback, daher ist diese onClick Methode hier nicht sinnvoll.

2021-04-26 16:34 UTC, DevNico commented on src/components/app/SortAttributes.tsx
> +		<Select open={open} onClose={handleClose} onOpen={handleOpen} defaultValue={1}>
Außerdem sollte man die Select props `name`, `value`, `onChange` und `onBlur` von außen übergeben können. Entweder lässt man einfach alle Select props zur übergabe von außen zu oder nur die oben genannten z.B. über den `Pick` utility type.

2021-05-03 13:20 UTC, Veronika-Starkulla commented
@DevNico done

2021-05-07 09:17 UTC, DevNico approved these changes

2021-05-10 07:22 UTC, merged