JS-35-InfoContainerGroup erstellt
ss21-js/ss21-js-frontend pull request #16
Opened 2021-05-05 18:05 UTC by Veronika-Starkulla

2021-05-07 09:08 UTC, DevNico commented on src/components/app/InfoContainerGroup.tsx
> +					</Grid>
Die einzelnen Elemente sollten dynamisch sein und von außen übergeben werden können.
e.g.
```ts
export interface InfoContainerGroupItem {
  title: string;
  content: string;
}
```
In den Props kann man dann eine Liste dieser Items übergeben.

2021-05-10 10:42 UTC, Veronika-Starkulla commented
@DevNico @cwehr96 done

2021-05-10 11:49 UTC, DevNico requested changes

2021-05-10 11:49 UTC, DevNico commented on src/components/app/InfoContainerGroup.tsx
> +	titel: string;
Bitte nur englische namen für variablen. z.B. `title`

2021-05-11 06:14 UTC, merged