Feature/js 56 profil header
ss21-js/ss21-js-frontend pull request #20
Opened 2021-05-27 12:16 UTC by cwehr96

Profileheader für die Profile Unternehmen und Student erstellt

2021-05-29 20:01 UTC, DevNico requested changes

2021-05-29 20:01 UTC, DevNico commented on src/components/profile/ProfileHeader.tsx
> +const ProfilHeader: React.FC<ProfilHeaderProps> = ({ firstName, lastName, companyName, type, adress }) => {
Auch hier bitte Englisch Profil**e**Header

2021-06-07 11:25 UTC, merged

2021-06-07 11:29 UTC, cwehr96 commented
@DevNico  das wurde mit gemerged bei dem einen obwohl ich das noch bearbeiten muss, weißt du wie man das richtig wieder Rückgänig machen kann ?

2021-06-07 12:45 UTC, cwehr96 commented
ich ändere das jetzt einfach nochmal und mergen das drauf dann passt das wieder...