Feature/js 59 about us company
ss21-js/ss21-js-frontend pull request #24
Opened 2021-05-27 12:25 UTC by cwehr96

Hier wurden #21 und #22  reingemerged

2021-05-29 19:47 UTC, DevNico requested changes

2021-05-29 19:47 UTC, DevNico commented on src/pages/Company/AboutUsCompnay.tsx
> +			</form>
Für Formulare sollten wir einheitlich `react-hook-form` einsetzen. Du kannst dir auf der LoginPage anschauen wie man das umsetzt.

Im Zusammenhang mit `react-hook-form` ist der `TextFieldContainer` dann auch nicht mehr ganz so sinnvoll.

2021-06-06 14:56 UTC, cwehr96 commented on src/pages/Company/AboutUsCompnay.tsx
> +			</form>
Habe ich geändert. Meintest du es so ? :)

2021-06-07 05:31 UTC, DevNico submitted a review, later dismissed

2021-06-07 14:19 UTC, Veronika-Starkulla approved these changes

2021-06-07 14:19 UTC, merged