Feature/js 54 unternehmens profil
ss21-js/ss21-js-frontend pull request #25
Opened 2021-05-27 12:33 UTC by cwehr96

Hier wurden #20 #24 und #23 reingemerged

2021-05-31 05:44 UTC, DevNico requested changes

2021-05-31 05:44 UTC, DevNico commented on src/pages/Company/AboutUsCompnay.tsx
> +const AboutUsCompnay: React.FC = () => {
AboutUsCompany

2021-05-31 05:44 UTC, DevNico commented on src/pages/Company/CompanyPage.tsx
> +const SavedPage: React.FC = () => {
Dateiname CompanyPage und default export SavedPage passen nicht zusammen.

2021-05-31 05:44 UTC, DevNico commented on src/pages/ProfilePage.tsx
> +			{/* TODO: Mit BE Daten füllen */}
Auch TODOs auf englisch.

2021-05-31 05:44 UTC, DevNico commented on src/pages/Company/ OpenJobOffers.tsx
> +const OpenJobOffers: React.FC = () => {
Leerzeichen am Anfang des Dateinamen und der Ordner Company gehört klein.

2021-05-31 05:44 UTC, DevNico commented on src/model/adress.ts
> +export interface Adress {
Address

2021-05-31 05:48 UTC, DevNico commented
Allgemein: Theme mehr integrieren / dark mode testen.

2021-06-05 08:11 UTC, cwehr96 commented
done @DevNico

2021-06-05 19:35 UTC, DevNico requested changes

2021-06-05 19:35 UTC, DevNico commented on src/pages/ProfilePage.tsx
>  			<ProfilHeader
ProfileHeader

2021-06-05 19:35 UTC, DevNico commented on src/components/profile/ProfileHeader.tsx
>  export interface ProfilHeaderProps {
ProfileHeaderProps

2021-06-05 19:35 UTC, DevNico commented on src/components/profile/ProfileHeader.tsx
> +const ProfilHeader: React.FC<ProfilHeaderProps> = ({ firstName, lastName, companyName, type, address }) => {
ProfileHeader

2021-06-06 15:09 UTC, cwehr96 commented
done 👍

2021-06-07 05:31 UTC, DevNico approved these changes

2021-06-07 11:25 UTC, merged