Feature/js 53 studenten profil
ss21-js/ss21-js-frontend pull request #27
Opened 2021-05-31 10:18 UTC by Veronika-Starkulla

2021-05-31 12:04 UTC, DevNico requested changes

2021-05-31 12:04 UTC, DevNico commented on src/model/profile/student.tsx
> +		}
Das sollte ein eigener Datentyp sein

2021-05-31 12:04 UTC, DevNico commented on src/model/profile/student.tsx
> +		}
Dann dementsprechend `experience: DatenTyp[],`

2021-05-31 12:04 UTC, DevNico commented on src/model/profile/student.tsx
> +		}
Sollte ein eigener Datentyp sein, `education: DatenTyp[],`

2021-05-31 12:04 UTC, DevNico commented on src/model/profile/student.tsx
> +	};
Mit Backend absprechen ob wir überhaupt social media verlinken vermutlich eher nicht.

2021-06-07 12:04 UTC, DevNico requested changes

2021-06-07 12:04 UTC, DevNico commented on src/model/jobhistory.tsx
> +export interface Jobhistory {
JobHistory

2021-06-07 12:28 UTC, Veronika-Starkulla commented
@DevNico done

2021-06-07 12:39 UTC, DevNico requested changes

2021-06-07 12:39 UTC, DevNico commented on src/pages/Student/ProfileGithub.tsx
> +	languages.map((language, index) => (fillLabels[index] = language.name));
Die `map` Funktion ist für die **Transformation** von Daten gedacht, du verwendest Sie hier eher wie eine `forEach` Funktion.

Das wäre eine besser Lösung, bei der die Daten direkt in das gewünschte Format transformiert werden.

```ts
const fillLabels = languages.map((language) => language.name);
const fillStats = languages.map((language) => language.count);
```

[Siehe auch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2021-06-07 12:39 UTC, DevNico commented on src/pages/Student/ProfileGithub.tsx
> +	const colors = ['#ff6384', '#36a2eb', '#ffce56', '#4bc0c0', '#9966ff', '#ff9f40'];
Für die Farben wäre eine lookup Tabelle schön in der für alle / so viele Sprachen wie möglich eine passende Farbe hinterlegt ist.

Ist aber nicht unbedingt notwendig, vielleicht gibt es sowas ja irgendwo schon muss aber nicht sein.

2021-06-07 12:39 UTC, DevNico commented on src/pages/Student/ProfileGithub.tsx
> +							text-align: -webkit-center;
Bitte kein vendor spezifisches css. Sowas sollte wenn überhaupt notwendig global für den css pre-processor konfiguriert werden.

2021-06-07 12:44 UTC, Veronika-Starkulla commented on src/pages/Student/ProfileGithub.tsx
> +	languages.map((language, index) => (fillLabels[index] = language.name));
Ohja, viel eleganter! Danke

2021-06-07 12:56 UTC, Veronika-Starkulla commented on src/pages/Student/ProfileGithub.tsx
> +	const colors = ['#ff6384', '#36a2eb', '#ffce56', '#4bc0c0', '#9966ff', '#ff9f40'];
Ja, da muss ich noch unbedingt eine bessere Lösung finden. Ich hab an 3 verschiedenen Stellen (colors, backgroundcolors und tags) dieselben Farben stehen. Muss noch schauen, wie ich es besser lösen kann.

2021-06-07 14:01 UTC, Veronika-Starkulla commented
@DevNico done

2021-06-07 14:20 UTC, DevNico approved these changes

2021-06-07 14:57 UTC, merged