Feature/js 33 collapsable container
ss21-js/ss21-js-frontend pull request #8
Opened 2021-04-19 14:37 UTC by cwehr96

- collapsable container added

2021-04-19 15:04 UTC, DevNico requested changes

2021-04-19 15:04 UTC, DevNico commented on src/components/app/CollapsableContainer.tsx
> +        ))}
Der spezifische use-case einer Job liste solle in einer separaten komponente ausgelagert werden.

2021-04-19 15:04 UTC, DevNico commented on src/store/general.ts
> +});
Globaler state hier nicht sinnvoll.

2021-04-19 15:09 UTC, DevNico requested changes

2021-04-19 15:09 UTC, DevNico commented on src/components/app/CollapsableContainer.tsx
> +        <ListItemText primary="Art der Anstellung" />
Titel sollte von außen übergeben werden können.

2021-04-20 14:08 UTC, cwehr96 commented
@DevNico done

2021-04-20 15:04 UTC, DevNico commented on src/components/app/CollapsableContainer.tsx
> +            max-width: 340px;
Ich denke nicht das man die max-width vorgeben sollte für einen generischen Container

2021-04-20 15:08 UTC, DevNico requested changes

2021-04-20 15:08 UTC, DevNico commented on src/components/app/CollapsableContainer.tsx
> +  children: React.ReactChild;
`React.ReactChild` erlaubt nur eine einzelne Komponente als child, ist das so gewollt? Falls nicht sollte man `React.ReactNode` verwenden.

2021-04-20 15:08 UTC, DevNico commented on src/components/app/JobList.tsx
> +}
Das Job interface sollte in den `src/models` Ordner ausgelagert werden.

2021-04-20 15:08 UTC, DevNico commented on src/components/app/JobList.tsx
> +const jobs: Job[] = [{name: "Vollzeitjob"},{name: "Teilzeitjob"},{name: "Praktikumsstelle"},{name: "Ausbildungsstelle"},{name: "Remotejob"}]
Auch die jobs sollten als prop übergeben werden können. Die jobs hier sind ja nur ein Platzhalter, könnte man z.b. `mockJobs` nennen und vorübergehend bis das Backend angebunden ist für die implementation der `JobList` exportieren.

2021-04-20 15:08 UTC, cwehr96 commented on src/components/app/CollapsableContainer.tsx
> +            max-width: 340px;
sorry, ja vergessen.

2021-04-20 15:11 UTC, cwehr96 commented on src/components/app/JobList.tsx
> +const jobs: Job[] = [{name: "Vollzeitjob"},{name: "Teilzeitjob"},{name: "Praktikumsstelle"},{name: "Ausbildungsstelle"},{name: "Remotejob"}]
Da hätte ich gesagt wartet man bis das Backend fertig ist aber gut pass ich an

2021-04-20 15:22 UTC, cwehr96 commented on src/components/app/CollapsableContainer.tsx
> +  children: React.ReactChild;
Hier würde ich aber sagen ist doch nur eins gewollt. Vielleicht überdenke ich auch gerade was aber mir fällt kein Grund für React.ReactNode ein? @DevNico

2021-04-20 16:41 UTC, DevNico commented on src/components/app/CollapsableContainer.tsx
> +  children: React.ReactChild;
Wenn das bewusst war passts, war mir nur nicht sicher.

2021-04-22 15:15 UTC, DevNico approved these changes

2021-04-22 15:18 UTC, merged